name: "Configure Action"
description: "Configure the .NET SDK before any other tasks"
inputs:
  cpp-sdk:
    description: "The C++ SDK file name"
    required: true
  shell:
    description: "The required shell"
    required: true
    default: bash
  
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - run: cmake -E make_directory ${{github.workspace}}/build
      shell: ${{ inputs.shell }}

    - name: Configure
      shell: ${{ inputs.shell }}
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{github.workspace}}

    - run: cmake -E make_directory ${{github.workspace}}/build/_deps/cppsdk-src/universal
      shell: ${{ inputs.shell }}
