name: Build and Test
on: [push]

jobs:
  build-n-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            sdk: cppsdk-2.0.0-macos64.zip
            shell: bash
          - os: windows-latest
            sdk: cppsdk-2.0.0-windows64.zip
            shell: powershell
    
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/configure
        with:
          cpp-sdk: ${{ matrix.sdk }}
          shell: ${{ matrix.shell }}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -VV -C RelWithDebInfo


