name: Build and Test
on: [push]

jobs:
  build-n-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            sdk: cppsdk-2.0.0-macos64.zip
          - os: windows-latest
            sdk: cppsdk-2.0.0-windows64.zip
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Get C++ SDK
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "DolbyIO/comms-sdk-cpp"
          tag: "2.0.0"
          fileName: "${{ matrix.sdk }}"
          out-file-path: "cppsdk"

      - run: 7z e ${{github.workspace}}/cppsdk.zip -o${{github.workspace}}/cppsdk

      - run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -DDOLBYIO_LIBRARY_PATH="${{github.workspace}}/cppsdk" -DCMAKE_BUILD_TYPE=RelWithDebugInfo ${{github.workspace}}

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Tests
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: ctest -vv


