name: Publish NuGet
on: workflow_dispatch

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/package.yml
        secrets: inherit
         
      - name: Download nuget artifact
        uses: actions/download-artifact@v3
        with:
          name: nugets

      - run: 7z e nugets.zip
        working-directory: ${{github.workspace}}/artifacts

      - name: Deploy to NuGet 🚀
        working-directory: ${{github.workspace}}/artifacts
        run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
