name: Publish NuGet
on: workflow_dispatch

jobs:
  package:
    uses: ./.github/workflows/package.yml
    secrets: inherit

  publish:
    runs-on: macos-latest
    needs: package
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Download nuget artifact
        uses: actions/download-artifact@v3
        with:
          name: nugets
          path: artifacts

      - name: Deploy to NuGet 🚀
        working-directory: artifacts
        run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
